version: '3.5'
services:
  database:
    container_name: mysql
    image: mysql:latest
    env_file: database.conf
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume: